name: Unzip File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (if any)
        run: pip install -r requirements.txt || true

      - name: Run unzip script
        run: python unzip_file.py
