name: Unzip Huawei Projects

on:
  workflow_dispatch:  # lets you manually trigger it

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show current files
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run unzip script
        run: python unzip_huawei.py
